# Version 1.0.0
version: "3"

services:
  app:
    build: images/nginx/${NGINX_VERSION}
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build: images/php/${PHP_VERSION}
    links:
      - db
    volumes: *appvolumes

  redis:
    image: redis:${REDIS_VERSION}

  db:
    image: ${DB_VERSION}
    ports:
      - "3306:3306"
    env_file: env/db.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: images/php/${PHP_VERSION}
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
  ssldata: